runtime: python27
threadsafe: true
api_version: 1
default_expiration: "14d"

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|svg|txt))$
  static_files: dist/ContentCalTT/\1
  upload: dist/ContentCalTT/(.*)
- url: /(.*)
  static_files: dist/ContentCalTT/index.html
  upload: dist/ContentCalTT/index.html